version: '3.8'

services:
  # Simple nginx web server as example
  app:
    image: nginx:alpine
    container_name: ${TUNNEL_NAME}-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:${SERVICE_PORT}:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - tunnel_network

  # Cloudflare tunnel sidecar
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: ${TUNNEL_NAME}-cloudflared
    restart: unless-stopped
    command: tunnel run
    networks:
      - tunnel_network
    volumes:
      - ../../cloudflared/config.yml:/home/nonroot/.cloudflared/config.yml:ro
      - ../../cloudflared/credentials.json:/home/nonroot/.cloudflared/credentials.json:ro
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "cloudflared", "tunnel", "info"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  tunnel_network:
    driver: bridge